### ISSUE TITLE
Add more Pokemon choices to use as pieces for TicTacToe

### ISSUE THREAD

**Issue by JordanNguyen** [UCSB-CS56-Projects/cs56-games-rock-paper-scissors#18]
Let the user select more than the current 3 Pokemon available to play with for TicTacToe (ie adding another Pokemon such as Pikachu to choose from). This also entails changing the GUI to display more choices efficiently if there gets to be too many Pokemon.

~Estimated 200

**Comment by mliou** [comment]
Approved.
